name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install jupyter nbconvert

    - name: Run and Convert Notebooks
      run: |
        jupyter nbconvert --execute --inplace Campus_Placement_Prediction_Using_ML.ipynb

    - name: Build Docker image
      run: docker build -t student_placement_model .

    - name: Push Docker image to GHCR
      run: |
        echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker tag student_placement_model ghcr.io/${{ github.repository_owner }}/student_placement_model:latest
        docker push ghcr.io/${{ github.repository_owner }}/student_placement_model:latest
