name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run model script
      run: python Campus_Placement_Prediction_Using_ML.ipynb

    - name: Build Docker image
      run: docker build -t ml-model .

    - name: Push Docker image
      run: |
        echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker tag ml-model ghcr.io/${{ github.repository_owner }}/ml-model:latest
        docker push ghcr.io/${{ github.repository_owner }}/ml-model:latest
